In [1]:
import numpy as np
arr = np.arange(8).reshape(2, 2, 2)
print(arr)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [2]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a.reshape(-1)
print(b)


[1 2 3 4 5 6]


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.sum(a, axis=0)
print(b)


[12 15 18]


In [4]:
a = np.array([[[0], [1], [2]]])
b = np.squeeze(a) 
print(b)


[0 1 2]


In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = x + y
print(z)


[5 7 9]


In [6]:
a = np.array([1, 2, 3])
b = np.array([0, 1, 0])
c = a * b
print(c)


[0 2 0]


In [7]:
a = np.array([1, 2, 3])
b = np.array([[0], [1], [2]])
c = a + b
print(c)


[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.sum(a, axis=1)
print(b)


[ 3  7 11]


In [9]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.mean(a)
print(b)


3.5


In [10]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.std(a, axis=0)
print(b)


[2.44948974 2.44948974 2.44948974]


In [11]:
import numpy as np
arr = np.arange(8).reshape(2, 2, 2)
print(arr)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a.reshape(-1)
print(b)


[1 2 3 4 5 6]


In [13]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.sum(a, axis=0)
print(b)


[12 15 18]


In [14]:
a = np.array([[[0], [1], [2]]])
b = np.squeeze(a)
print(b)


[0 1 2]


In [15]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = x + y
print(z)


[5 7 9]


In [16]:
a = np.array([1, 2, 3])
b = np.array([0, 1, 0])
c = a * b
print(c)


[0 2 0]


In [17]:
a = np.array([1, 2, 3])
b = np.array([[0], [1], [2]])
c = a + b
print(c)


[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [18]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.sum(a, axis=1)
print(b)


[ 3  7 11]


In [19]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.mean(a)
print(b)


3.5


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.std(a, axis=0)
print(b)


[2.44948974 2.44948974 2.44948974]


In [21]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a.T
print(b)


[[1 3 5]
 [2 4 6]]


In [22]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a.reshape(2, 3)
print(b)


[[1 2 3]
 [4 5 6]]


In [23]:
a = np.array([1, 2, 3])
b = np.expand_dims(a, axis=1)
print(b)


[[1]
 [2]
 [3]]


In [24]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = a ** b
print(c)


[ 1  8 81]


In [25]:
a = np.array([10, 20, 30])
b = np.array([3, 7, 5])
c = a % b
print(c)


[1 6 0]


In [26]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
c = a > b
print(c)


[False False  True]


In [27]:
a = np.array([1, 2, 3, 4])
b = np.cumsum(a)
print(b)


[ 1  3  6 10]


In [28]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.prod(a, axis=0)
print(b)


[15 48]


In [29]:
a = np.array([[7, 2, 9], [3, 5, 1], [4, 8, 6]])
b = np.min(a, axis=1)
print(b)


[2 1 4]


In [30]:
a = np.array([10, 15, 5, 7])
b = np.argmax(a)
print(b)


1


In [31]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dot(a, b)

print(c)


32


In [32]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = a.T

print(b[0][1])


3


In [33]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = a[::-1]

print(b[1])


3


In [34]:
import numpy as np

a = np.array([1.1, 2.2, 3.3, 4.4])
b = a.astype(int)

print(b)


[1 2 3 4]


In [35]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()

print(b[4])


5


In [36]:
import numpy as np

a = np.zeros((2, 3))
a[0, 1] = 5
a[1, 2] = 7

print(a)


[[0. 5. 0.]
 [0. 0. 7.]]


In [37]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = a.sum(axis=0)

print(b)


[ 9 12]


In [38]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
c = np.multiply(a, b)

print(c)


[ 2  6 12 20]
